apiVersion: apps/v1
kind: Deployment
metadata:
  name: transponder-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transponder-scanner
  template:
    metadata:
      labels:
        app: transponder-scanner
    spec:
      containers:
        - name: transponder-scanner
          command:
            - "transponder"
            - "scanner"
          args:
            - "--config-file=/etc/transponder/scanner.yaml"
          image: eu.gcr.io/jetstack-wil/transponder:0.0.1
          volumeMounts:
            - name: scanner-config
              mountPath: /etc/transponder
              readOnly: true
      volumes:
        - name: scanner-config
          configMap:
            name: scanner-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-config
data:
  scanner.yaml: |
    # This is an example config file for the Transponder Scanner that uses the Server's default port numbers.
    servers:
      - host: transponder-server
        ports:
          - protocol: HTTP
            number: 8080
          - protocol: HTTPS
            number: 8443
          - protocol: GRPC
            number: 8081
