apiVersion: apps/v1
kind: Deployment
metadata:
  name: transponder-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transponder-server
  template:
    metadata:
      labels:
        app: transponder-server
    spec:
      containers:
        - name: transponder-server
          command:
            - "transponder"
            - "server"
          args:
            - "--http-port=8080"
            - "--grpc-port=8081"
            - "--https-port=8443"
          image: quay.io/wwwil/transponder:v0.0.1
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8443
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: transponder-server
  labels:
    app: transponder-server
spec:
  type: ClusterIP
  selector:
    app: transponder-server
  ports:
    - port: 8080
      name: http-transponder-server
    - port: 8081
      name: grpc-transponder-server
    - port: 8443
      name: https-transponder-server
