apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: istio-system
data:
  Corefile: |
    k8s.example.com:53 {
      log
      rewrite stop {
        name regex (.*)\.zone1\.k8s\.example\.com {1}.svc.cluster.local
        answer name (.*)\.svc\.cluster\.local {1}.zone1.k8s.example.com
      }
      forward . /etc/resolv.conf
    }
    .:53 {
      errors
      health
      
      grpc global 127.0.0.1:8053
      forward . /etc/resolv.conf {
        except global
      }
      
      prometheus :9153
      cache 30
      reload
    }
